# Generated by Django 6.0.6 on 2026-07-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
